server:
  port: 8005

spring:
   application:
    name: microservicecloud-test

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservicecloud-test-8005
    prefer-ip-address: true

info:
  app.name: wwj-microservicecloud
  company.name: www.wwj.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$